// Generated by CoffeeScript 1.12.7

/*
Fetch all root CAs
 */
var all, asn1, crypto, der, each, forge, pki, seen, sha1;

crypto = require('crypto');

forge = require('node-forge');

pki = forge.pki;

asn1 = forge.asn1;

each = require('./each');

module.exports = all = [];

sha1 = function(data) {
  return crypto.createHash('sha1').update(data, 'binary').digest('hex');
};

der = function(crt) {
  return asn1.toDer(pki.certificateToAsn1(crt)).getBytes();
};

seen = {};

each(function(crt) {
  var z;
  if (seen[z = sha1(der(crt))]) {
    return;
  }
  seen[z] = 1;
  return all.push(crt);
});

seen = 0;
