// Generated by CoffeeScript 1.12.7

/*
Enumerate system root CAs synchronously
 */
var crypt;

crypt = require('./crypt32');

module.exports = function(storeName, cb) {
  var ctx, store;
  if (typeof storeName === 'function') {
    cb = storeName;
    storeName = 'ROOT';
  }
  if (Array.isArray(storeName)) {
    storeName.forEach(function(sn) {
      return module.exports(sn, cb);
    });
    return;
  }
  store = crypt.CertOpenSystemStoreA(null, storeName);
  try {
    ctx = null;
    while (1) {
      ctx = crypt.CertEnumCertificatesInStore(store, ctx);
      if (ctx.isNull()) {
        return;
      }
      cb(ctx.deref().crt());
    }
  } finally {
    crypt.CertCloseStore(store, 0);
  }
};
