// Generated by CoffeeScript 1.12.7

/*
Format parts of certificate
 */
var pem, pki, self, subject, valid;

pki = require('node-forge').pki;

self = require('../package');

this.subject = subject = function(crt) {
  return crt.subject.attributes.map(function(rdn) {
    return "/" + (rdn.shortName || rdn.name || rdn.type) + "=" + rdn.value;
  });
};

subject.join = '';

this.valid = valid = function(crt) {
  var k, ref, results, v;
  ref = crt.validity;
  results = [];
  for (k in ref) {
    v = ref[k];
    results.push(v.toISOString());
  }
  return results;
};

valid.join = ' - ';

this.saved = function() {
  var d;
  d = new Date;
  return (d.toLocaleDateString()) + " " + (d.toTimeString().replace(/\s*\(.*\)\s*/, '')) + " by " + self.name + "@" + self.version;
};

this.pem = pem = function(crt) {
  return pki.certificateToPem(crt);
};

pem.title = false;
