// Generated by CoffeeScript 1.12.7

/*
X509_NAME_hash_old
 */
var asn1, crypto, encode, forge, md5, pki;

crypto = require('crypto');

forge = require('node-forge');

pki = forge.pki;

asn1 = forge.asn1;

encode = function(dn) {
  return asn1.toDer(pki.distinguishedNameToAsn1(dn)).getBytes();
};

md5 = function(data) {
  return crypto.createHash('md5').update(data, 'binary').digest();
};

module.exports = function(dn) {
  return md5(encode(dn)).readUInt32LE(0);
};
