// Generated by CoffeeScript 1.12.7

/*
X509_NAME_hash
 */
var asn1, canon, crypto, encode, forge, pki, sha1, stripSeq;

crypto = require('crypto');

forge = require('node-forge');

pki = forge.pki;

asn1 = forge.asn1;

canon = function(dn) {
  return {
    attributes: dn.attributes.map(function(rdn) {
      return {
        valueTagClass: asn1.Type.UTF8,
        type: rdn.type,
        value: rdn.value.toLowerCase().replace(/\s+/g, ' ').replace(/^\s+|\s+$/, '')
      };
    })
  };
};

stripSeq = function(buffer) {
  buffer.getByte();
  asn1.getBerValueLength(buffer);
  return buffer.getBytes();
};

encode = function(dn) {
  return stripSeq(asn1.toDer(pki.distinguishedNameToAsn1(canon(dn))));
};

sha1 = function(data) {
  return crypto.createHash('sha1').update(data, 'binary').digest();
};

module.exports = function(dn) {
  return sha1(encode(dn)).readUInt32LE(0);
};
