// Generated by CoffeeScript 1.12.7
require('./format.oids');

this.all = function() {
  return require('./all');
};

require('./inject');

this.path = require('./save').path;

this.each = require('./each');

this.async = function(cb) {
  return require('./async')(cb);
};
