// Generated by CoffeeScript 1.12.7

/*
Inject Root CAs into Node.js
 */
var base, ca, crt, forge, https, i, len, pki, ref;

https = require('https');

forge = require('node-forge');

pki = forge.pki;

ca = (base = https.globalAgent.options).ca || (base.ca = []);

ref = require('./all');
for (i = 0, len = ref.length; i < len; i++) {
  crt = ref[i];
  ca.push(pki.certificateToPem(crt));
}
